"""RGB-TIR data and Qwen3-VL adaptation primitives for the AIC project."""

from .data import (
    ManifestBundle,
    RGBTRecord,
    build_manifest_bundle,
    build_tracer_records,
    write_jsonl,
)
from .modeling import (
    AsymmetricLoRALinear,
    NormalizedBBoxHead,
    Qwen3VLRGBTAdapter,
    RGBTVisionOutput,
    RGBTTIRWarmupFeatures,
    RGBTTIRValidationFeatures,
    RGBTTIRRepairFeatures,
    ZeroInitResidualFusion,
    install_asymmetric_lora,
)
from .phase1 import (
    BBoxAwareTIRAlignmentLoss,
    QwenVisionAssetPlan,
    build_roi_patch_weights,
    download_qwen_vision_assets,
    load_qwen3vl_vision_only,
    freeze_for_tir_adapter_warmup,
    freeze_for_rgbtir_inference,
    load_tir_adapter_state_dict,
    parameter_sha256,
    read_qwen_vision_asset_plan,
    tir_adapter_state_dict,
    trainable_parameter_summary,
)
from .phase15 import Phase15Config, Phase15Result, Phase15Validator
from .phase16 import (
    CandidateSpec,
    DeterministicNegativeSampler,
    Phase16Config,
    Phase16RepairObjective,
    Phase16RepairTrainer,
    Phase16Result,
    RGBTeacherBank,
    RepairSplit,
    TeacherEntry,
    build_repair_split,
)
from .phase17a_plus import (
    DECISION_BRANCHES,
    Phase17APlusAuditor,
    Phase17APlusResult,
    Phase17Decision,
    Phase17DecisionInputs,
    Phase17DecisionPolicy,
)
from .phase18 import (
    D1CandidateSpec,
    D1RetentionObjective,
    Phase18Config,
    Phase18RetentionProbe,
    Phase18Result,
    evaluate_retention_metrics,
)
from .phase18_full import (
    CheckpointArtifact,
    Phase18FullConfig,
    Phase18FullResult,
    Phase18FullRunner,
)
from .phase18r_audit import Phase18RAuditConfig, Phase18RAuditor, Phase18RAuditResult
from .query_probe import QueryCandidate, QueryInterfaceSmoke, QuerySmokeResult
from .processing import PairedRGBTBatch, PairedRGBTProcessor, SharedGeometryTransform

__all__ = [
    "AsymmetricLoRALinear",
    "ManifestBundle",
    "NormalizedBBoxHead",
    "PairedRGBTBatch",
    "PairedRGBTProcessor",
    "Qwen3VLRGBTAdapter",
    "RGBTRecord",
    "RGBTVisionOutput",
    "RGBTTIRWarmupFeatures",
    "RGBTTIRValidationFeatures",
    "RGBTTIRRepairFeatures",
    "BBoxAwareTIRAlignmentLoss",
    "QwenVisionAssetPlan",
    "Phase15Config",
    "Phase15Result",
    "Phase15Validator",
    "CandidateSpec",
    "DeterministicNegativeSampler",
    "Phase16Config",
    "Phase16RepairObjective",
    "Phase16RepairTrainer",
    "Phase16Result",
    "RGBTeacherBank",
    "RepairSplit",
    "TeacherEntry",
    "build_repair_split",
    "DECISION_BRANCHES",
    "Phase17APlusAuditor",
    "Phase17APlusResult",
    "Phase17Decision",
    "Phase17DecisionInputs",
    "Phase17DecisionPolicy",
    "D1CandidateSpec",
    "D1RetentionObjective",
    "Phase18Config",
    "Phase18RetentionProbe",
    "Phase18Result",
    "evaluate_retention_metrics",
    "CheckpointArtifact",
    "Phase18FullConfig",
    "Phase18FullResult",
    "Phase18FullRunner",
    "Phase18RAuditConfig",
    "Phase18RAuditor",
    "Phase18RAuditResult",
    "QueryCandidate",
    "QueryInterfaceSmoke",
    "QuerySmokeResult",
    "build_roi_patch_weights",
    "download_qwen_vision_assets",
    "load_qwen3vl_vision_only",
    "freeze_for_tir_adapter_warmup",
    "freeze_for_rgbtir_inference",
    "install_asymmetric_lora",
    "load_tir_adapter_state_dict",
    "parameter_sha256",
    "read_qwen_vision_asset_plan",
    "tir_adapter_state_dict",
    "trainable_parameter_summary",
    "SharedGeometryTransform",
    "ZeroInitResidualFusion",
    "build_manifest_bundle",
    "build_tracer_records",
    "write_jsonl",
]
